### ISSUE TITLE
python3.11 crossover

### ISSUE THREAD

**Issue by PingalPie** [brentvollebregt/auto-py-to-exe#458]
**Quick Checks**

- [x] I have read the [help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe)
- [x] I have [searched other issues](https://github.com/brentvollebregt/auto-py-to-exe/issues?q=is%3Aissue+), looking for an issue similar to mine

**Describe the bug**

autopytoexe does not work in python3.11 as autopytoexe imports `getargspec` from `inspect` module which was removed in python3.11 

**To Reproduce**

1. Install python3.11
2. Run auto-py-to-exe from cli

```bash
auto-py-to-exe
```
Error: 
```
Traceback (most recent call last):
  File "$HOME/.local/bin/auto-py-to-exe", line 5, in <module>
    from auto_py_to_exe.__main__ import run
  File "$HOME/.local/lib/python3.11/site-packages/auto_py_to_exe/__main__.py", line 13, in <module>
    from . import ui
  File "$HOME/.local/lib/python3.11/site-packages/auto_py_to_exe/ui.py", line 6, in <module>
    import eel
  File "$HOME/.local/lib/python3.11/site-packages/eel/__init__.py", line 15, in <module>
    import bottle as btl
  File "/usr/lib/python3/dist-packages/bottle.py", line 44, in <module>
    from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

```

**Expected behavior**

Run perfectly fine

**Your Environment:**

- Python version (`python --version`): 3.11.5
- auto-py-to-exe version (`pip show auto-py-to-exe`): 2.42.0
- PyInstaller version (`pip show pyinstaller`): 6.3.0
- Eel version (`pip show eel`): 0.16.0

**Comment by brentvollebregt** [comment]
What version of `bottle` do you have installed? I recommend trying 0.12.25.

**Comment by PingalPie** [comment]
I was using bottle: 0.12.15
after updating bottle to 0.12.25
it was solved and worked perfectly fine
