### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TemporaryDirectory'

### ISSUE THREAD

**Issue by HabButterimAuge** [brentvollebregt/auto-py-to-exe#38]
After I downloaded it from GitHub, installed it and opened it, an error occured:
Traceback (most recent call last):
  File "/usr/local/bin/auto-py-to-exe", line 11, in <module>
    load_entry_point('auto-py-to-exe==2.4.3', 'console_scripts', 'auto-py-to-exe')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/auto_py_to_exe-2.4.3-py2.7.egg/auto_py_to_exe/__main__.py", line 107, in <module>
    temporary_directory = tempfile.TemporaryDirectory()
AttributeError: 'module' object has no attribute 'TemporaryDirectory'

I installed it with "python setup.py install". I have python 2.7.15+ and python 3.6.7. I use Kali Linux 2018!
Thx

**Comment by brentvollebregt** [comment]
Ah yes, I had assumed this new feature would work with Python 2.7 but never tested it. `tempfile.TemporaryDirectory` was added in Python 3.2 so I will need to use something a bit older to keep support for Python 2.7.

**Comment by brentvollebregt** [comment]
I believe I have fixed this issue at  6b056be and have merged the branch it was on into master.

Could you please test this and verify that the temporary directory is being created and deleted when the project is closed? The temporary directory will be displayed in the output when packaging a script.

**Comment by HabButterimAuge** [comment]
Now another error occurs:
`Traceback (most recent call last):
  File "/usr/local/bin/auto-py-to-exe", line 7, in <module>
    from auto_py_to_exe.__main__ import run
  File "/usr/local/lib/python2.7/dist-packages/auto_py_to_exe/__main__.py", line 21, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
`

**Comment by brentvollebregt** [comment]
Are you testing using the latest on master? I thought I had fixed this quite a while ago.

**Comment by HabButterimAuge** [comment]
Yes

**Comment by HabButterimAuge** [comment]
fixed it by doing the installation with python2.7. But after I want to start the program the console is "loading" but nothing happen nothing. I have installed chrome <a href=https://linuxconfig.org/how-to-install-google-chrome-browser-on-kali-linux>with</a> this tutorial

**Comment by brentvollebregt** [comment]
Wasn't Python 2.7 the original issue? You now have me confused; all these tracebacks are Python 2.7.

You stating that you have to install Chrome using a tutorial is hinting to me that this cannot find your Chrome distribution. Although when using Linux, Eel picks up `google-chrome` so it should be launching. Are you seeing any warnings?

**Comment by HabButterimAuge** [comment]
Sorry that was my fault^^ I installed the program now on windows 10, there it was verry easy:)

**Comment by brentvollebregt** [comment]
Oh that's good. I'm still a bit curious about Kali Linux though, next time I'm using it I'll try it myself.

I'll close the issue for now but if anything comes up in regards to this issue, we can open it back up.
